spring:
  profiles:
    active: ${profile}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 56100
  servlet:
    context-path: /api

apollo:
  versionName: ${versionName}
  ks3:
    endpoint: ks3-cn-beijing.ksyun.com
  redis:
    expiration: 7200
    prefix:
      authCode: ${profile}:authCode
      phoneCode: ${profile}:loginCode
      ticketCode: ${profile}:ticket
  uid:
    seed: 10000
    step: 200