spring:
  datasource:
    url: jdbc:postgresql://data:5432/fasion
    username: admin
    password: fasion
  redis:
    database: 1
    host: redis
    port: 6379

minerva:
  ks3:
    bucket-name: test-data
    bucket-domain: test-data.ks3-cn-beijing.ksyun.com
    access-key: AKLTu_NfS8S0RZOpyEkV0Jh9-w
    secret-key: OE/6cEgGKlHhuzZFTOtiQqfMef8cq0uoR6ptMDNYe46PHzboQKnn6HLWkCMgTIR32A==
  mercury:
    url: http://pay:56400/api